### ISSUE TITLE
week 04 - day 01 - Octocats

### ISSUE THREAD

**Issue by mdewey** [Dantezinfern0/assignments#12]
# React-ified Octocats

Your task is to refactor the static Octodex into a static (non-API) version using React.

You'll identify the main `Component`s on the page and create React components for each, breaking down those `Component`s into smaller ones as needed.

## Objectives

- Learn to identify parts of a web site as `Component`s
- Use `app-app` (GAMMA stack) to build a React project
- Understand and use React components

## Stretch Objectives

- Understand and use "props" in React
- Use `Array.prototype.map` to render a collection of components in React

### Explorer Mode

- [x] [Use this HTML and CSS](https://gist.github.com/mdewey/963d50c11ee90054d1542fd4957e2e9e) as a starting point
- [x] Figure out the main components of the page. These will be the main components in your `<App>` component.
- [x] You should have at _least_ two components...
- [x] Create your React app
- [x] Copy the CSS from the template into `index.css`
- [x] Clear out the implementation in the `render` method of `App` and have it render your main components.
- [x] Create those components and paste the appropriate HTML from the Octodex into the `render` method of those components.
- [x] Break down those components and use `this.props` to dynamically customize the components that need it.

### Adventure Mode

- [x] Place the definition of each Octocat in an `array` and use `map` to generate the Octocat components

### Epic Mode

- [ ] Put the `array` of Octocats in an `octocats.json` file and `import` that into your app.
- _OR_
- [ ] Use the `fetch` API to retrieve the list of Octocats from [this api](https://sdg-octodex.herokuapp.com/) instead

## Additional Resources

- [React Documentation](https://reactjs.org/docs/getting-started.html)
- [.map, .reduce & .filter, Oh My!](https://www.datchley.name/working-with-collections/)
- [Array.prototype.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

**Comment by Dantezinfern0** [comment]
https://github.com/Dantezinfern0/react-i

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e11f1f3541d668540d195fe7adcb68fd773344b8/giphy-12.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/77)**__
