### ISSUE TITLE
career support - trello - Trello for jobs

### ISSUE THREAD

**Issue by ktrammell95** [Dantezinfern0/assignments#16]
# Create a Trello card for one job

In this assignment, you will create a Trello card for a job that you found interesting. This can be for your dream job or just something that sounded interesting to you.

## Card Requirements

- [x] Company name - job title
- [x] Description of the company
- [x] Company website link
- [x] Location
- [x] Link to the job description

- Add comments:
- [ ] What is their narrative?
- [ ] Why do you like this company?
- [ ] Why did you like this posting?
- [ ] How might you benefit them?

## Turning in your assignment

- To turn in this assignement you will move your card to "Ready for Rec" and tag Katherine (@ktrammellsdg) in a comment on that card with the wording "Ready for a Rec"
- Copy and paste the link to your card as a comment on this issue

## Due Date

- This assignment is due by 9 am on Friday, May 31st.

**Comment by Dantezinfern0** [comment]
I put the card in the 'doing' "folder"?  I don't think I like them or think that I could benefit them and they are looking for a senior but I didn't iknow it was a part of the assignment to take the time to find a company that I really actually wanted to work for .  I think I just need more advisement on what I was supposed to do here.  I did familiarize myself with trello.

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--337d5db9d88e083c06c448999f852548342972b5/giphy-18.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/83)**__
