### ISSUE TITLE
week 05 - day 01 - mineswept

### ISSUE THREAD

**Issue by mdewey** [Dantezinfern0/assignments#17]
# A mine!

This morning we did a couple of code reviews. Take these lessons and finish up your minesweeper apps. 

Also, we have been exploring react for the past week. Let's take those skills and upgrade some old projects. 

## Objectives

- With your new knowledge, finish minesweeper
- Update an old project using React. 

### Explorer Mode

- [x] Finish your minesweeper
- [ ] Go back to project to a project unit-i (week 1 through 3)

### Adventure Mode

- [ ] Work on any previous adventure or epic mode of any previous homework
- [ ] Go back and redo an old project.

**Comment by Dantezinfern0** [comment]
https://github.com/Dantezinfern0/mine-sweeper.git

&&

https://github.com/Dantezinfern0/black-rejackt.git

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
