### ISSUE TITLE
career support - resumes - Build your Resume

### ISSUE THREAD

**Issue by ktrammell95** [Dantezinfern0/assignments#21]
Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [ ] Portfolio link

## Summary 
- [x]  Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” simply use a headline that encapsulates your credentials.

## Skills 
- [x]  You’ll want to incorporate the right keywords so that your resume is optimized for application tracking systems

## Professional experience
- [x]  Focus on your accomplishments rather than your day-to-day responsibilities

## Education
- [x]  Simply write where you went college and your degree.
- [x]  It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ]  Volunteering and community service

## Due Date: Wednesday, June 19th
- [ ]  Upload or submit a link to your resume for review.

**Comment by Dantezinfern0** [comment]
[DanteHarasz.pdf](https://github.com/Dantezinfern0/assignments/files/3307322/DanteHarasz.pdf)

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3c87e39487e11776789d2fa19615334abd2e3aab/giphy-1.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/66)**__
