### ISSUE TITLE
week 07 - day 04  - EF and Koans

### ISSUE THREAD

**Issue by mdewey** [Dantezinfern0/assignments#29]
# ORM Safari!

We are taking a surprise trip to the Savannah for a safari to see all sorts of exotic animals. During our time on safari, we want to keep track of all the animals we have seen. For this, we need to create a database, as well as a small console application to help record what we see.

## Objectives

- Use an ORM to query against a database

### Additional Reading

_NOTE_: The Additional Resources section below is _very_ helpful. Consider reading this after reading _Explorer_ mode. Then make a plan for the assignment for digging in and writing code.

### Explorer Mode - Part 1

- [ ] Create a database called `SafariVacation`
  - [ ] This will have 1 table called `SeenAnimals` that has the following columns
    - `Id` (int)
    - `Species` (string)
    - `CountOfTimesSeen` (int)
    - `LocationOfLastSeen` (string)
  * NOTE: This should be made all in the code (C#), and **not** created in the `pgcli`.
- [ ] Create a small console application, and create the following queries using your languages ORM.
  - [ ] Display all animals the user has seen
  - [ ] Update the `CountOfTimesSeen` and `LocationOfLastSeen` for an animal
  - [ ] Display all animals seen in the `Jungle`
  - [ ] Remove all animals that I have seen in the `Desert`.
  - [ ] Add all the `CountOfTimesSeen` and get a total number of animals seen
  - [ ] Get the `CountOfTimesSeen` of `lions`, `tigers` and `bears`

### Explorer Mode - part 2 

- [ ] Work on the Koans.

### Adventure Mode 

- [ ] Add a new column called `LastSeenTime`, with a type of DateTime. This will require you to add and run a new migration.

### Epic Mode

- [ ] Continue to make progress on your capstone project.

### .NET

Here are the interesting commands you will need for tonight's assignment

- To add Entity Framework to your project:

```
 dotnet add package Microsoft.EntityFrameworkCore.Design 

 dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL
```

- To create your database:

```
createdb <<DatabaseName>>
```

- To create the DbContext

```
dotnet ef dbcontext scaffold "server=localhost;database=<<DatabaseName>>" Npgsql.EntityFrameworkCore.PostgreSQL -c <<DatabaseName>>Context

```

- Add a migration:

```
 dotnet ef migrations add AddBaordGameTable
```

- Update your database

```
dotnet ef database update
```

- Documentation: [Dotnet EF CLI Docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)
- Useful C# Notes: [Lecture Notes](https://suncoast.io/handbook/curriculum/back-end/full-stack-i/lecture/dotnet/)

**Comment by Dantezinfern0** [comment]
https://github.com/Dantezinfern0/DotNetCoreKoans
